// Code generated by go-swagger; DO NOT EDIT.

package sensor

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gios-api-client/models"
)

// AirQualityIndexReader is a Reader for the AirQualityIndex structure.
type AirQualityIndexReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AirQualityIndexReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAirQualityIndexOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAirQualityIndexOK creates a AirQualityIndexOK with default headers values
func NewAirQualityIndexOK() *AirQualityIndexOK {
	return &AirQualityIndexOK{}
}

/*AirQualityIndexOK handles this case with default header values.

successful operation
*/
type AirQualityIndexOK struct {
	Payload *models.AirQualityIndexResponse200
}

func (o *AirQualityIndexOK) Error() string {
	return fmt.Sprintf("[GET /aqindex/getIndex/{stationId}][%d] airQualityIndexOK  %+v", 200, o.Payload)
}

func (o *AirQualityIndexOK) GetPayload() *models.AirQualityIndexResponse200 {
	return o.Payload
}

func (o *AirQualityIndexOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AirQualityIndexResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
