// Code generated by go-swagger; DO NOT EDIT.

package stations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/michalq/go-gios-api-client/models"
)

// AllStationsReader is a Reader for the AllStations structure.
type AllStationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AllStationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAllStationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewAllStationsOK creates a AllStationsOK with default headers values
func NewAllStationsOK() *AllStationsOK {
	return &AllStationsOK{}
}

/*AllStationsOK handles this case with default header values.

Ok
*/
type AllStationsOK struct {
	Payload models.StationsResponse200
}

func (o *AllStationsOK) Error() string {
	return fmt.Sprintf("[GET /station/findAll][%d] allStationsOK  %+v", 200, o.Payload)
}

func (o *AllStationsOK) GetPayload() models.StationsResponse200 {
	return o.Payload
}

func (o *AllStationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
