// Code generated by go-swagger; DO NOT EDIT.

package stations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAllStationsParams creates a new AllStationsParams object
// with the default values initialized.
func NewAllStationsParams() *AllStationsParams {

	return &AllStationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAllStationsParamsWithTimeout creates a new AllStationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAllStationsParamsWithTimeout(timeout time.Duration) *AllStationsParams {

	return &AllStationsParams{

		timeout: timeout,
	}
}

// NewAllStationsParamsWithContext creates a new AllStationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAllStationsParamsWithContext(ctx context.Context) *AllStationsParams {

	return &AllStationsParams{

		Context: ctx,
	}
}

// NewAllStationsParamsWithHTTPClient creates a new AllStationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAllStationsParamsWithHTTPClient(client *http.Client) *AllStationsParams {

	return &AllStationsParams{
		HTTPClient: client,
	}
}

/*AllStationsParams contains all the parameters to send to the API endpoint
for the all stations operation typically these are written to a http.Request
*/
type AllStationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the all stations params
func (o *AllStationsParams) WithTimeout(timeout time.Duration) *AllStationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the all stations params
func (o *AllStationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the all stations params
func (o *AllStationsParams) WithContext(ctx context.Context) *AllStationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the all stations params
func (o *AllStationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the all stations params
func (o *AllStationsParams) WithHTTPClient(client *http.Client) *AllStationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the all stations params
func (o *AllStationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AllStationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
