// Code generated by go-swagger; DO NOT EDIT.

package stations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new stations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for stations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AllStations gets all stations
*/
func (a *Client) AllStations(params *AllStationsParams) (*AllStationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAllStationsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "AllStations",
		Method:             "GET",
		PathPattern:        "/station/findAll",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &AllStationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*AllStationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for AllStations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
SensorData sensors in station

Returns available sensors in specific station
*/
func (a *Client) SensorData(params *SensorDataParams) (*SensorDataOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSensorDataParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "SensorData",
		Method:             "GET",
		PathPattern:        "/station/sensors/{stationId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SensorDataReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*SensorDataOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for SensorData: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
