// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SensorParam sensor param
// swagger:model SensorParam
type SensorParam struct {

	// id param
	IDParam int64 `json:"idParam,omitempty"`

	// param code
	ParamCode AcquisitionType `json:"paramCode,omitempty"`

	// param formula
	ParamFormula string `json:"paramFormula,omitempty"`

	// param name
	ParamName string `json:"paramName,omitempty"`
}

// Validate validates this sensor param
func (m *SensorParam) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParamCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SensorParam) validateParamCode(formats strfmt.Registry) error {

	if swag.IsZero(m.ParamCode) { // not required
		return nil
	}

	if err := m.ParamCode.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("paramCode")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SensorParam) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SensorParam) UnmarshalBinary(b []byte) error {
	var res SensorParam
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
