// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Sensor sensor
// swagger:model Sensor
type Sensor struct {

	// id
	ID int64 `json:"id,omitempty"`

	// param
	Param *SensorParam `json:"param,omitempty"`

	// station Id
	StationID int64 `json:"stationId,omitempty"`
}

// Validate validates this sensor
func (m *Sensor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParam(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Sensor) validateParam(formats strfmt.Registry) error {

	if swag.IsZero(m.Param) { // not required
		return nil
	}

	if m.Param != nil {
		if err := m.Param.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("param")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Sensor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Sensor) UnmarshalBinary(b []byte) error {
	var res Sensor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
