// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SensorAcquisition sensor acquisition
// swagger:model SensorAcquisition
type SensorAcquisition struct {

	// date
	// Required: true
	Date string `json:"date"`

	// value
	// Required: true
	Value float32 `json:"value"`
}

// Validate validates this sensor acquisition
func (m *SensorAcquisition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SensorAcquisition) validateDate(formats strfmt.Registry) error {

	if err := validate.RequiredString("date", "body", string(m.Date)); err != nil {
		return err
	}

	return nil
}

func (m *SensorAcquisition) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", float32(m.Value)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SensorAcquisition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SensorAcquisition) UnmarshalBinary(b []byte) error {
	var res SensorAcquisition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
